cache:
  directories:
  - $HOME/.m2

language: java

dist: trusty

jdk:
- oraclejdk8

script: "mvn clean package cobertura:cobertura"

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
